version: "3"

services:
  target-one:
    image: shillaker/hoststats:${VERSION}
    volumes:
      - .:/code/hoststats
    expose:
      - "5000"
    command: /bin/bash -c "cd /code/hoststats && pip install -e . && hoststats start"
    environment:
      HOSTSTATS_SLEEP_INTERVAL_MS: "500"

  target-two:
    image: shillaker/hoststats:${VERSION}
    volumes:
      - .:/code/hoststats
    expose:
      - "5000"
    command: /bin/bash -c "cd /code/hoststats && pip install -e . && hoststats start"
    environment:
      HOSTSTATS_SLEEP_INTERVAL_MS: "500"

  target-three:
    image: shillaker/hoststats:${VERSION}
    volumes:
      - .:/code/hoststats
    expose:
      - "5000"
    command: /bin/bash -c "cd /code/hoststats && pip install -e . && hoststats start"
    environment:
      HOSTSTATS_SLEEP_INTERVAL_MS: "500"

  client:
    image: shillaker/hoststats:${VERSION}
    volumes:
      - .:/code/hoststats
    depends_on:
      - target-one
      - target-two
      - target-three
    command: /bin/bash
