version: "3"

services:
  target-one:
    image: shillaker/hoststats:${VERSION}
    expose:
      - "5000"
    environment:
      HOSTSTATS_SLEEP_INTERVAL_MS: "500"

  target-two:
    image: shillaker/hoststats:${VERSION}
    expose:
      - "5000"
    environment:
      HOSTSTATS_SLEEP_INTERVAL_MS: "500"

  target-three:
    image: shillaker/hoststats:${VERSION}
    expose:
      - "5000"
    environment:
      HOSTSTATS_SLEEP_INTERVAL_MS: "500"

  client:
    image: shillaker/hoststats:${VERSION}
    depends_on:
      - target-one
      - target-two
      - target-three
